export const REGISTER_URL = 'http://localhost:1337/api/users/register'
export const LOGIN_URL = 'http://localhost:1337/api/users/login'
export const USERS_URL = 'http://localhost:1337/api/users'
export const CATEGORIES_URL = 'http://localhost:1337/api/categories'
export const PRODUCTS_URL = 'http://localhost:1337/api/products/category='
export const PRODUCT_GET_BY_ID_URL = 'http://localhost:1337/api/products/product='
export const PRODUCT_PROMO_URL = 'http://localhost:1337/api/products/promo'
export const PRODUCT_NEW_URL = 'http://localhost:1337/api/products/new'
