export const REGISTER_URL = 'http://localhost:1337/api/users/register'
export const LOGIN_URL = 'http://localhost:1337/api/users/login'
export const USERS_URL = 'http://localhost:1337/api/users'
export const CATEGORIES_URL = 'http://localhost:1337/api/categories'
export const PRODUCTS_URL = 'http://localhost:1337/api/products/'
